version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tarefas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: gerenciador_tarefas_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data: